import fs from 'node:fs';
import path from 'node:path';

export interface CredentialField {
  key: string;
  label: string;
  isSecret?: boolean;
  defaultValue?: string;
  validator?: (val: string) => boolean | string;
}

export interface SecurityCheckResult {
  isSafe: boolean;
  warnings: string[];
}

export class CredentialManager {
  /**
   * Validates database credentials for security violations (e.g. using root/admin account)
   */
  static validateDbSecurity(username: string): SecurityCheckResult {
    const dangerousUsers = ['root', 'admin', 'administrator', 'sa', 'superuser'];
    const lower = username.trim().toLowerCase();
    
    if (dangerousUsers.includes(lower)) {
      return {
        isSafe: false,
        warnings: [
          `[보안 경고] 관리자 계정('${username}')을 에이전트 MCP에 직접 연결하는 것은 극히 위험합니다.`,
          `반드시 SELECT 권한만 부여된 'readonly' 전용 계정을 발급하여 사용하십시오.`,
          `SQL 예시: CREATE USER 'readonly'@'...' IDENTIFIED BY '...'; GRANT SELECT ON db.* TO 'readonly'@'...';`
        ]
      };
    }

    return { isSafe: true, warnings: [] };
  }

  /**
   * Safely writes credentials to a secure global file (~/.ax/.env.mcp) or target directory
   * with restrictive file permissions (chmod 600)
   */
  static saveSecureEnv(targetDir?: string, envMap: Record<string, string> = {}): string {
    const { GlobalPaths } = require('./paths.js');
    const envPath = targetDir ? path.join(targetDir, '.env.mcp') : GlobalPaths.getGlobalEnvPath();
    
    // Ensure parent dir exists
    const parentDir = path.dirname(envPath);
    if (!fs.existsSync(parentDir)) {
      fs.mkdirSync(parentDir, { recursive: true });
    }

    const lines: string[] = [
      '# ⚠️ WARNING: Confidential Global MCP Credentials. NEVER commit to Git.',
      `# Generated by ax-onboarding at ${new Date().toISOString()}`,
      ''
    ];

    for (const [k, v] of Object.entries(envMap)) {
      lines.push(`${k}=${v}`);
    }

    // chmod 600 (safe on Windows as well via Node.js fs)
    try {
      fs.writeFileSync(envPath, lines.join('\n') + '\n', { mode: 0o600 });
    } catch {
      fs.writeFileSync(envPath, lines.join('\n') + '\n');
    }
    
    if (targetDir) {
      this.ensureGitignored(targetDir, '.env.mcp');
    }

    return envPath;
  }

  /**
   * Ensures the given entry is listed in .gitignore
   */
  static ensureGitignored(targetDir: string, entry: string): void {
    const gitignorePath = path.join(targetDir, '.gitignore');
    let content = '';
    if (fs.existsSync(gitignorePath)) {
      content = fs.readFileSync(gitignorePath, 'utf-8');
    }

    const lines = content.split('\n').map(l => l.trim());
    if (!lines.includes(entry)) {
      const addition = content.endsWith('\n') || content.length === 0 ? entry + '\n' : '\n' + entry + '\n';
      fs.appendFileSync(gitignorePath, addition, 'utf-8');
    }
  }
}
