import fs from 'node:fs';
import path from 'node:path';
import os from 'node:os';

export class RollbackManager {
  /**
   * Restores ~/.claude.json from backup if available, and cleans generated files in targetDir
   */
  static rollback(targetDir = process.cwd()): { restoredFiles: string[]; deletedFiles: string[] } {
    const restoredFiles: string[] = [];
    const deletedFiles: string[] = [];

    // 1. Restore ~/.claude.json
    const claudeJsonPath = path.join(os.homedir(), '.claude.json');
    const backupPath = `${claudeJsonPath}.bak_axonboard`;

    if (fs.existsSync(backupPath)) {
      fs.copyFileSync(backupPath, claudeJsonPath);
      fs.unlinkSync(backupPath);
      restoredFiles.push(claudeJsonPath);
    }

    // 2. Clean up targetDir files generated by ax-onboard
    const filesToClean = [
      path.join(targetDir, 'CLAUDE.md'),
      path.join(targetDir, 'AGENTS.md'),
      path.join(targetDir, '.env.mcp')
    ];

    for (const f of filesToClean) {
      if (fs.existsSync(f)) {
        fs.unlinkSync(f);
        deletedFiles.push(f);
      }
    }

    // 3. Clean runbooks directory if exists
    const runbooksDir = path.join(targetDir, 'runbooks');
    if (fs.existsSync(runbooksDir)) {
      fs.rmSync(runbooksDir, { recursive: true, force: true });
      deletedFiles.push(runbooksDir);
    }

    return { restoredFiles, deletedFiles };
  }
}
